name: Build Android App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Create web content
      run: |
        mkdir -p client/dist/public
        echo '<!DOCTYPE html><html><head><title>Cognitive Elite Pro</title></head><body><h1>Brain Games</h1></body></html>' > client/dist/public/index.html
        
    - name: Build AAB
      run: |
        cd android
        chmod +x gradlew
        ./gradlew bundleRelease
        
    - name: Upload AAB
      uses: actions/upload-artifact@v4
      with:
        name: app-release.aab
        path: android/app/build/outputs/bundle/release/app-release.aab
